<?xml version="1.0" encoding="utf-8"?><Database Name="QLShopTheThao" Class="QLSQADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-1IAEAGU\SQLEXPRESS;Initial Catalog=QLShopTheThao;Integrated Security=True" SettingsObjectName="QLShopTheThao.Properties.Settings" SettingsPropertyName="QLShopTheThaoConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.db_ChiTietDonHang" Member="db_ChiTietDonHangs">
    <Type Name="db_ChiTietDonHang">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="db_HoaDon_db_ChiTietDonHang" Member="db_HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="db_HoaDon" IsForeignKey="true" />
      <Association Name="db_SanPham_db_ChiTietDonHang" Member="db_SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="db_SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.db_HoaDon" Member="db_HoaDons">
    <Type Name="db_HoaDon">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="db_HoaDon_db_ChiTietDonHang" Member="db_ChiTietDonHangs" ThisKey="MaHD" OtherKey="MaHD" Type="db_ChiTietDonHang" />
      <Association Name="db_KhachHang_db_HoaDon" Member="db_KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="db_KhachHang" IsForeignKey="true" />
      <Association Name="db_User_db_HoaDon" Member="db_User" ThisKey="MaNV" OtherKey="MaNV" Type="db_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.db_KhachHang" Member="db_KhachHangs">
    <Type Name="db_KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiKH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sdtKH" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="GioiTInh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EmailKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="db_KhachHang_db_HoaDon" Member="db_HoaDons" ThisKey="MaKH" OtherKey="MaKH" Type="db_HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.db_SanPham" Member="db_SanPhams">
    <Type Name="db_SanPham">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoLuongSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaSP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AnhSP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="db_SanPham_db_ChiTietDonHang" Member="db_ChiTietDonHangs" ThisKey="MaSP" OtherKey="MaSP" Type="db_ChiTietDonHang" />
    </Type>
  </Table>
  <Table Name="dbo.db_User" Member="db_Users">
    <Type Name="db_User">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EmailDK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Vaitro" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="GioiTinhDK" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="db_User_db_HoaDon" Member="db_HoaDons" ThisKey="MaNV" OtherKey="MaNV" Type="db_HoaDon" />
    </Type>
  </Table>
</Database>