#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLShopTheThao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLShopTheThao")]
	public partial class QLSQADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdb_ChiTietDonHang(db_ChiTietDonHang instance);
    partial void Updatedb_ChiTietDonHang(db_ChiTietDonHang instance);
    partial void Deletedb_ChiTietDonHang(db_ChiTietDonHang instance);
    partial void Insertdb_HoaDon(db_HoaDon instance);
    partial void Updatedb_HoaDon(db_HoaDon instance);
    partial void Deletedb_HoaDon(db_HoaDon instance);
    partial void Insertdb_KhachHang(db_KhachHang instance);
    partial void Updatedb_KhachHang(db_KhachHang instance);
    partial void Deletedb_KhachHang(db_KhachHang instance);
    partial void Insertdb_SanPham(db_SanPham instance);
    partial void Updatedb_SanPham(db_SanPham instance);
    partial void Deletedb_SanPham(db_SanPham instance);
    partial void Insertdb_User(db_User instance);
    partial void Updatedb_User(db_User instance);
    partial void Deletedb_User(db_User instance);
    #endregion
		
		public QLSQADataContext() : 
				base(global::QLShopTheThao.Properties.Settings.Default.QLShopTheThaoConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public QLSQADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSQADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSQADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSQADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<db_ChiTietDonHang> db_ChiTietDonHangs
		{
			get
			{
				return this.GetTable<db_ChiTietDonHang>();
			}
		}
		
		public System.Data.Linq.Table<db_HoaDon> db_HoaDons
		{
			get
			{
				return this.GetTable<db_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<db_KhachHang> db_KhachHangs
		{
			get
			{
				return this.GetTable<db_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<db_SanPham> db_SanPhams
		{
			get
			{
				return this.GetTable<db_SanPham>();
			}
		}
		
		public System.Data.Linq.Table<db_User> db_Users
		{
			get
			{
				return this.GetTable<db_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.db_ChiTietDonHang")]
	public partial class db_ChiTietDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private int _MaSP;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<double> _ThanhTien;
		
		private EntityRef<db_HoaDon> _db_HoaDon;
		
		private EntityRef<db_SanPham> _db_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<double> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public db_ChiTietDonHang()
		{
			this._db_HoaDon = default(EntityRef<db_HoaDon>);
			this._db_SanPham = default(EntityRef<db_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._db_HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._db_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_HoaDon_db_ChiTietDonHang", Storage="_db_HoaDon", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public db_HoaDon db_HoaDon
		{
			get
			{
				return this._db_HoaDon.Entity;
			}
			set
			{
				db_HoaDon previousValue = this._db_HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._db_HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._db_HoaDon.Entity = null;
						previousValue.db_ChiTietDonHangs.Remove(this);
					}
					this._db_HoaDon.Entity = value;
					if ((value != null))
					{
						value.db_ChiTietDonHangs.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(string);
					}
					this.SendPropertyChanged("db_HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_SanPham_db_ChiTietDonHang", Storage="_db_SanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public db_SanPham db_SanPham
		{
			get
			{
				return this._db_SanPham.Entity;
			}
			set
			{
				db_SanPham previousValue = this._db_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._db_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._db_SanPham.Entity = null;
						previousValue.db_ChiTietDonHangs.Remove(this);
					}
					this._db_SanPham.Entity = value;
					if ((value != null))
					{
						value.db_ChiTietDonHangs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(int);
					}
					this.SendPropertyChanged("db_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.db_HoaDon")]
	public partial class db_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private int _MaNV;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<System.DateTime> _NgayBan;
		
		private System.Nullable<double> _TongTien;
		
		private EntitySet<db_ChiTietDonHang> _db_ChiTietDonHangs;
		
		private EntityRef<db_KhachHang> _db_KhachHang;
		
		private EntityRef<db_User> _db_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnNgayBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBanChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    #endregion
		
		public db_HoaDon()
		{
			this._db_ChiTietDonHangs = new EntitySet<db_ChiTietDonHang>(new Action<db_ChiTietDonHang>(this.attach_db_ChiTietDonHangs), new Action<db_ChiTietDonHang>(this.detach_db_ChiTietDonHangs));
			this._db_KhachHang = default(EntityRef<db_KhachHang>);
			this._db_User = default(EntityRef<db_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._db_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._db_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBan
		{
			get
			{
				return this._NgayBan;
			}
			set
			{
				if ((this._NgayBan != value))
				{
					this.OnNgayBanChanging(value);
					this.SendPropertyChanging();
					this._NgayBan = value;
					this.SendPropertyChanged("NgayBan");
					this.OnNgayBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_HoaDon_db_ChiTietDonHang", Storage="_db_ChiTietDonHangs", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<db_ChiTietDonHang> db_ChiTietDonHangs
		{
			get
			{
				return this._db_ChiTietDonHangs;
			}
			set
			{
				this._db_ChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_KhachHang_db_HoaDon", Storage="_db_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public db_KhachHang db_KhachHang
		{
			get
			{
				return this._db_KhachHang.Entity;
			}
			set
			{
				db_KhachHang previousValue = this._db_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._db_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._db_KhachHang.Entity = null;
						previousValue.db_HoaDons.Remove(this);
					}
					this._db_KhachHang.Entity = value;
					if ((value != null))
					{
						value.db_HoaDons.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("db_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_User_db_HoaDon", Storage="_db_User", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public db_User db_User
		{
			get
			{
				return this._db_User.Entity;
			}
			set
			{
				db_User previousValue = this._db_User.Entity;
				if (((previousValue != value) 
							|| (this._db_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._db_User.Entity = null;
						previousValue.db_HoaDons.Remove(this);
					}
					this._db_User.Entity = value;
					if ((value != null))
					{
						value.db_HoaDons.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("db_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_db_ChiTietDonHangs(db_ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.db_HoaDon = this;
		}
		
		private void detach_db_ChiTietDonHangs(db_ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.db_HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.db_KhachHang")]
	public partial class db_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenKH;
		
		private string _DiaChiKH;
		
		private string _sdtKH;
		
		private System.Nullable<bool> _GioiTInh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _EmailKH;
		
		private EntitySet<db_HoaDon> _db_HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiKHChanging(string value);
    partial void OnDiaChiKHChanged();
    partial void OnsdtKHChanging(string value);
    partial void OnsdtKHChanged();
    partial void OnGioiTInhChanging(System.Nullable<bool> value);
    partial void OnGioiTInhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnEmailKHChanging(string value);
    partial void OnEmailKHChanged();
    #endregion
		
		public db_KhachHang()
		{
			this._db_HoaDons = new EntitySet<db_HoaDon>(new Action<db_HoaDon>(this.attach_db_HoaDons), new Action<db_HoaDon>(this.detach_db_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKH", DbType="NVarChar(100)")]
		public string DiaChiKH
		{
			get
			{
				return this._DiaChiKH;
			}
			set
			{
				if ((this._DiaChiKH != value))
				{
					this.OnDiaChiKHChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKH = value;
					this.SendPropertyChanged("DiaChiKH");
					this.OnDiaChiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtKH", DbType="VarChar(15)")]
		public string sdtKH
		{
			get
			{
				return this._sdtKH;
			}
			set
			{
				if ((this._sdtKH != value))
				{
					this.OnsdtKHChanging(value);
					this.SendPropertyChanging();
					this._sdtKH = value;
					this.SendPropertyChanged("sdtKH");
					this.OnsdtKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTInh", DbType="Bit")]
		public System.Nullable<bool> GioiTInh
		{
			get
			{
				return this._GioiTInh;
			}
			set
			{
				if ((this._GioiTInh != value))
				{
					this.OnGioiTInhChanging(value);
					this.SendPropertyChanging();
					this._GioiTInh = value;
					this.SendPropertyChanged("GioiTInh");
					this.OnGioiTInhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailKH", DbType="NVarChar(50)")]
		public string EmailKH
		{
			get
			{
				return this._EmailKH;
			}
			set
			{
				if ((this._EmailKH != value))
				{
					this.OnEmailKHChanging(value);
					this.SendPropertyChanging();
					this._EmailKH = value;
					this.SendPropertyChanged("EmailKH");
					this.OnEmailKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_KhachHang_db_HoaDon", Storage="_db_HoaDons", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<db_HoaDon> db_HoaDons
		{
			get
			{
				return this._db_HoaDons;
			}
			set
			{
				this._db_HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_db_HoaDons(db_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.db_KhachHang = this;
		}
		
		private void detach_db_HoaDons(db_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.db_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.db_SanPham")]
	public partial class db_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSP;
		
		private string _TenSP;
		
		private System.Nullable<int> _SoLuongSP;
		
		private System.Nullable<double> _GiaSP;
		
		private string _AnhSP;
		
		private EntitySet<db_ChiTietDonHang> _db_ChiTietDonHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnSoLuongSPChanging(System.Nullable<int> value);
    partial void OnSoLuongSPChanged();
    partial void OnGiaSPChanging(System.Nullable<double> value);
    partial void OnGiaSPChanged();
    partial void OnAnhSPChanging(string value);
    partial void OnAnhSPChanged();
    #endregion
		
		public db_SanPham()
		{
			this._db_ChiTietDonHangs = new EntitySet<db_ChiTietDonHang>(new Action<db_ChiTietDonHang>(this.attach_db_ChiTietDonHangs), new Action<db_ChiTietDonHang>(this.detach_db_ChiTietDonHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(100)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongSP", DbType="Int")]
		public System.Nullable<int> SoLuongSP
		{
			get
			{
				return this._SoLuongSP;
			}
			set
			{
				if ((this._SoLuongSP != value))
				{
					this.OnSoLuongSPChanging(value);
					this.SendPropertyChanging();
					this._SoLuongSP = value;
					this.SendPropertyChanged("SoLuongSP");
					this.OnSoLuongSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSP", DbType="Float")]
		public System.Nullable<double> GiaSP
		{
			get
			{
				return this._GiaSP;
			}
			set
			{
				if ((this._GiaSP != value))
				{
					this.OnGiaSPChanging(value);
					this.SendPropertyChanging();
					this._GiaSP = value;
					this.SendPropertyChanged("GiaSP");
					this.OnGiaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhSP", DbType="NVarChar(MAX)")]
		public string AnhSP
		{
			get
			{
				return this._AnhSP;
			}
			set
			{
				if ((this._AnhSP != value))
				{
					this.OnAnhSPChanging(value);
					this.SendPropertyChanging();
					this._AnhSP = value;
					this.SendPropertyChanged("AnhSP");
					this.OnAnhSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_SanPham_db_ChiTietDonHang", Storage="_db_ChiTietDonHangs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<db_ChiTietDonHang> db_ChiTietDonHangs
		{
			get
			{
				return this._db_ChiTietDonHangs;
			}
			set
			{
				this._db_ChiTietDonHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_db_ChiTietDonHangs(db_ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.db_SanPham = this;
		}
		
		private void detach_db_ChiTietDonHangs(db_ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.db_SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.db_User")]
	public partial class db_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _TenNV;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _EmailDK;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _Vaitro;
		
		private System.Nullable<bool> _GioiTinhDK;
		
		private EntitySet<db_HoaDon> _db_HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailDKChanging(string value);
    partial void OnEmailDKChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnVaitroChanging(string value);
    partial void OnVaitroChanged();
    partial void OnGioiTinhDKChanging(System.Nullable<bool> value);
    partial void OnGioiTinhDKChanged();
    #endregion
		
		public db_User()
		{
			this._db_HoaDons = new EntitySet<db_HoaDon>(new Action<db_HoaDon>(this.attach_db_HoaDons), new Action<db_HoaDon>(this.detach_db_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailDK", DbType="VarChar(50)")]
		public string EmailDK
		{
			get
			{
				return this._EmailDK;
			}
			set
			{
				if ((this._EmailDK != value))
				{
					this.OnEmailDKChanging(value);
					this.SendPropertyChanging();
					this._EmailDK = value;
					this.SendPropertyChanged("EmailDK");
					this.OnEmailDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vaitro", DbType="NChar(10)")]
		public string Vaitro
		{
			get
			{
				return this._Vaitro;
			}
			set
			{
				if ((this._Vaitro != value))
				{
					this.OnVaitroChanging(value);
					this.SendPropertyChanging();
					this._Vaitro = value;
					this.SendPropertyChanged("Vaitro");
					this.OnVaitroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhDK", DbType="Bit")]
		public System.Nullable<bool> GioiTinhDK
		{
			get
			{
				return this._GioiTinhDK;
			}
			set
			{
				if ((this._GioiTinhDK != value))
				{
					this.OnGioiTinhDKChanging(value);
					this.SendPropertyChanging();
					this._GioiTinhDK = value;
					this.SendPropertyChanged("GioiTinhDK");
					this.OnGioiTinhDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="db_User_db_HoaDon", Storage="_db_HoaDons", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<db_HoaDon> db_HoaDons
		{
			get
			{
				return this._db_HoaDons;
			}
			set
			{
				this._db_HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_db_HoaDons(db_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.db_User = this;
		}
		
		private void detach_db_HoaDons(db_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.db_User = null;
		}
	}
}
#pragma warning restore 1591
